Reworked the `flake8 <https://flake8.pycqa.org/>`__ configuration in CI, which was previously only checking a few
errors due to a misconfiguration.
